---
include:
  - board: eyelash_sofle_dongle
    shield: nice_view
  - board: eyelash_sofle_left
    shield: nice_view
  - board: eyelash_sofle_right
    shield: nice_view
  - board: eyelash_sofle_dongle
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_dongle
  - board: eyelash_sofle_dongle
    shield: settings_reset
